### ISSUE TITLE
Начать проект

### ISSUE THREAD

**Issue by WinterCitizen** [WinterCitizen/Debt#1]
Создать Django приложение которое:
* Содержит `requirements.txt`, в котором находятся все зависимости необходимые для поднятия проекта
* Поднимается после установки зависимостей и показывает весёлую дефолтную джанговскую страничку в корне сайта

**Comment by DOORAAD** [comment]
Что за зависимости?

**Comment by WinterCitizen** [comment]
@DOORAAD, зависимости это python пакеты, которые устанавливаются с помощью пакетного менеджера `pip`. Например `pip install django` устанавливает пакет `django` и всё что ему необходимо. `pip freeze` показывает все установленные пакеты, именно это ты должен использовать для создания `requirements.txt`
