### ISSUE TITLE
Посмотреть на Django модели

### ISSUE THREAD

**Issue by WinterCitizen** [WinterCitizen/Debt#5]
Необходимо посмотреть джанго [документацию на модели](https://docs.djangoproject.com/en/2.2/topics/db/models/), [принципы работы реляционных баз данных](https://habr.com/ru/post/193136/) и [основы SQL](https://habr.com/ru/post/305926/).

Результатом исполнения таска являются:
* Пул реквест с моделью представляющей "долг"
* Комментарий в этом таске содержащий `SQL` запросы которые будут выполняться при:
  * Создании таблицы долгов
  * Создания записи долга
  * Обновления записи долга

Если не сможешь найти интересующей тебя информации в ссылках выше, пиши в этом таске.

**Comment by WinterCitizen** [comment]
@DOORAAD совсем забыл. У сократики есть лучшие видосы по всему на свете. В том числе про [SQL](https://youtu.be/OfM5lC-7R4Y?list=PLi01XoE8jYojRqM4qGBF1U90Ee1Ecb5tt)

**Comment by DOORAAD** [comment]
```sql
CREATE TABLE Debt
(
    first_name varchar(30)
    last_name varchar(30)
    debt_amount integer

);
INSERT INTO Debt(first_name, last_name, debt_amount)
VALUES ('Anton', 'Sychev', 20000);

UPDATE Debt
SET first_name='Andrey', last_name='Erokhin', debt_amount=50000
WHERE pk=1;
```
